import { Project, CustomPhase, OopCost, createProductionManagementPhase } from './types';

export type BenchmarkCategory =
'Animation' | 'Edit & Audio' | 'XR' | 'Digital Art' | 'Live & Virtual Events';

export interface BenchmarkRoleHours {
  roleId: string;
  hours: number;
}

export interface BenchmarkTactic {
  id: string;
  category: BenchmarkCategory;
  name: string;
  description: string;
  oopDescription?: string;
  oopItemName?: string;
  oopItemAmount?: number;
  roleHours: BenchmarkRoleHours[];
}

export const BENCHMARK_CATEGORIES: BenchmarkCategory[] = [
  'Animation', 'Edit & Audio', 'XR', 'Digital Art', 'Live & Virtual Events'
];

export const BENCHMARK_TACTICS: BenchmarkTactic[] = [
  {
    id: 'animated_convention_panel_level_1',
    category: 'Animation',
    name: 'Animated Convention Panel - Level 1',
    description: 'Looping video for use as digital signage at conference. Up to 10 screens of animated content included.',
    oopDescription: 'Up to 10 screens of content\nAnimation to utilize predesigned page layouts\nno 3d animation included',
    roleHours: [{ roleId: 'senior_motion_graphics_designer', hours: 70 }, { roleId: 'senior_producer', hours: 40 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'director_motion_graphics', hours: 2 }, { roleId: 'junior_motion_gfx_designer', hours: 2 }],
  },
  {
    id: 'animated_patient_video_level_1',
    category: 'Animation',
    name: 'Animated Patient Video - Level 1',
    description: 'Created a 3-5 minute animated film utilizing a real patient’s voice as the narration',
    oopDescription: 'Includes remote audio recording of real patient\n Includes up to 20 Illustrations generated for storyboard and use in animation\nIncludes timing cut, 2D animation,\nAudio Mix and sound design. VO and music license costs not included.',
    oopItemName: 'Remote Audio Record',
    oopItemAmount: 2000,
    roleHours: [{ roleId: 'supervising_animation_director', hours: 205 }, { roleId: 'senior_producer', hours: 155 }, { roleId: 'senior_digital_artist', hours: 150 }, { roleId: 'director_digital_art', hours: 35 }, { roleId: 'senior_video_editor', hours: 16 }, { roleId: 'audio_engineer', hours: 12 }, { roleId: 'junior_video_editor', hours: 4 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'director_motion_graphics', hours: 2 }, { roleId: 'junior_motion_gfx_designer', hours: 2 }, { roleId: 'dir_video_services_vp', hours: 1 }],
  },
  {
    id: 'animated_instructions_for_use_explainer_video_animated',
    category: 'Animation',
    name: 'Animated Instructions for Use / Explainer Video - Animated',
    description: 'Create a simple 2-4 minute animated instructions for use video. Uses simple illustrations or existing product photography.',
    oopDescription: '\nFully-animated content with simple graphics and titles, 1 x voice-over, and stock music. \nBased on a 14 week schedule including client and legal reviews and final wrap.\nTraffic hours include creation of Ad-ID, element storage management and ADA Compliancy (Closed Caption/Audio Description for Hearing / Visually Impaired',
    roleHours: [{ roleId: 'senior_motion_graphics_designer', hours: 70 }, { roleId: 'senior_producer', hours: 60 }, { roleId: 'senior_digital_artist', hours: 56 }, { roleId: 'director_digital_art', hours: 14 }, { roleId: 'audio_engineer', hours: 6 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'director_motion_graphics', hours: 2 }, { roleId: 'junior_motion_gfx_designer', hours: 2 }],
  },
  {
    id: 'animated_sizzle_video_internal_excitement_poa_video',
    category: 'Animation',
    name: 'Animated Sizzle Video / Internal Excitement / POA Video',
    description: 'Final Deliverable: Full production 3-5 minute high energy video generated from existing content\n\nAnimated Video. All assets and artwork provided by agency (stock imagery, PSD files, etc). Music search, pro VO talent record and final mix',
    roleHours: [{ roleId: 'senior_motion_graphics_designer', hours: 105 }, { roleId: 'senior_producer', hours: 60 }, { roleId: 'senior_video_editor', hours: 16 }, { roleId: 'audio_engineer', hours: 6 }, { roleId: 'junior_video_editor', hours: 4 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'director_motion_graphics', hours: 2 }, { roleId: 'dir_video_services_vp', hours: 1 }],
  },
  {
    id: 'social_original_animated_post_basic',
    category: 'Animation',
    name: 'Social - Original Animated Post (Low Complexity)',
    description: '(1) New animated video Post. Includes scrolling or static ISI. Content up to :30 secs long. With ISI, length is up to 2 minutes. -',
    oopDescription: 'Based on storyboard with provideed art assets\n-Includes scrolling ISI\n-No Audio\n- Assumes all licensing costs covered under other budgets',
    roleHours: [{ roleId: 'motion_graphics_designer', hours: 21 }, { roleId: 'senior_producer', hours: 18 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'director_motion_graphics', hours: 2 }, { roleId: 'junior_motion_gfx_designer', hours: 2 }],
  },
  {
    id: 'social_campaign_adaptation_video_post_basic_level',
    category: 'Animation',
    name: 'Social - Campaign Adaptation Video Post (Low Complexity)',
    description: '(1) New video Post created with video assets lifted from existing campaign. Includes scrolling or static ISI. Content up to :30 secs long. With ISI, length is up to 2 minutes. Updated to reflect Offshore pricing',
    oopDescription: 'Based on storyboard with provideed art assets \n-Includes scrolling ISI \n-1 Stock music Track or pickup from campaign\n- Assumes all licensing costs covered under other budgets',
    roleHours: [{ roleId: 'producer_offshore_brazil', hours: 16 }, { roleId: 'motion_graphics_designer_off_shore_brazil', hours: 16 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'audio_engineer', hours: 2 }, { roleId: 'junior_motion_gfx_designer', hours: 2 }, { roleId: 'animation_director_off_shore_brazil', hours: 2 }],
  },
  {
    id: 'social_reformat_animated_post_basic_level',
    category: 'Animation',
    name: 'Social - Reformat Animated Post (Low Complexity)',
    description: 'Reformating of video post. For example, conversion of Facebook Feed post to Instagram post. - Updated to reflect Offshore Pricing.',
    oopDescription: 'Assumes no changes to content or timing\n- Aspect ratio change \n- Minor layout changes\n- Assumes all licensing costs covered under other budgets\n\n',
    roleHours: [{ roleId: 'producer_offshore_brazil', hours: 13 }, { roleId: 'motion_graphics_designer_off_shore_brazil', hours: 8 }, { roleId: 'junior_motion_gfx_designer', hours: 2 }, { roleId: 'svp_director_of_production', hours: 1 }, { roleId: 'animation_director_off_shore_brazil', hours: 1 }],
  },
  {
    id: 'isi_label_update',
    category: 'Animation',
    name: 'ISI/Label Update',
    description: 'Update ISI and codes for 10 to 20 video tactics. - Updated to reflect Offshore Pricing. Bumped Producer hrs up +15',
    oopDescription: 'Assumes use of same ISI elements across all tactics, VO rerecord of ISI, all updates done at same time.\nTraffic hours include creation of ten to twenty (10-20) Ad-ID\'s, element storage management and ADA Compliancy (Closed Caption/Audio Description for Hearing / Visually Impaired. \nTOS/OOP may vary based on ISI video length and ADA requirements.\n\nIncludes \nOne (1) round of client review and revisions\nOne (1) round of MLR submissions and One (1) Final/2253 Submission',
    roleHours: [{ roleId: 'motion_graphics_designer_off_shore_brazil', hours: 40 }, { roleId: 'producer_offshore_brazil', hours: 35 }, { roleId: 'animation_director_off_shore_brazil', hours: 10 }, { roleId: 'audio_engineer', hours: 6 }, { roleId: 'svp_director_of_production', hours: 4 }],
  },
  {
    id: '3d_moa_mod',
    category: 'Animation',
    name: '3D MOA/MOD',
    description: '3 minute 3D highscience animated MOA/MOD video - Bumped Producer hrs up to 150',
    oopDescription: '• Includes time for creation of Initial sketches, art for Storyboard, 3-5 Styleframes\n• Includes time to model all needed 3D characters and environments\n• Includes all 3D animation\n• Includes design and animation of 2D elements such as titles and on-screen graphics \n• Includes record/mix • Includes additional OOP for $2,500  \n**Does not include OOP costs for talent or stock music',
    oopItemName: 'Render Farm/Models',
    oopItemAmount: 2500,
    roleHours: [{ roleId: 'senior_3d_artist', hours: 280 }, { roleId: 'senior_producer', hours: 210 }, { roleId: 'supervising_animation_director', hours: 130 }, { roleId: 'supervising_medical_illustrator', hours: 100 }, { roleId: 'director_computer_graphics', hours: 70 }, { roleId: 'senior_video_editor', hours: 16 }, { roleId: 'audio_engineer', hours: 8 }, { roleId: 'svp_director_of_production', hours: 5 }, { roleId: 'junior_video_editor', hours: 4 }, { roleId: 'director_motion_graphics', hours: 2 }, { roleId: 'dir_video_services_vp', hours: 1 }],
  },
  {
    id: '2d_moa_mod',
    category: 'Animation',
    name: '2D MOA/MOD',
    description: '3 minute 2D simplified science animated MOA/MOD video - Bumped Producer hrs up to 110',
    oopDescription: '• Includes time for Medical Illustration research\n• Includes time for creation of Initial sketches, art for Storyboard, 3-5 Styleframes\n• Includes time to illustrate all needed 2D characters and environments\n• Includes all 2D animation\n• Includes design and animation of 2D elements such as titles and on-screen graphics \n **Does not include OOP costs for talent or stock music',
    roleHours: [{ roleId: 'supervising_animation_director', hours: 250 }, { roleId: 'senior_producer', hours: 150 }, { roleId: 'supervising_medical_illustrator', hours: 100 }, { roleId: 'senior_video_editor', hours: 16 }, { roleId: 'audio_engineer', hours: 8 }, { roleId: 'svp_director_of_production', hours: 5 }, { roleId: 'junior_video_editor', hours: 4 }, { roleId: 'director_motion_graphics', hours: 2 }, { roleId: 'dir_video_services_vp', hours: 1 }],
  },
  {
    id: 'simple_show_gfx_package',
    category: 'Animation',
    name: 'Low Complexity Show GFX Package',
    description: 'Basic costs for Low Complexity Show GFX Package',
    oopDescription: '• Includes Open/Close Animation\n• Animated Lower Thirds \n• Standby Screen / Pre-Show Loop',
    roleHours: [{ roleId: 'senior_motion_graphics_designer', hours: 37 }, { roleId: 'senior_producer', hours: 25 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'director_motion_graphics', hours: 2 }, { roleId: 'junior_motion_gfx_designer', hours: 2 }],
  },
  {
    id: 'complex_show_gfx_package',
    category: 'Animation',
    name: 'High Complexity Show GFX Package',
    description: 'Basic costs for High Complexity Show GFX Package',
    oopDescription: '• Includes Open/Close Animation\n• Animated Lower Thirds \n• Additional Animated Show Elements. • Standby Screen / Pre-Show Loop',
    roleHours: [{ roleId: 'senior_motion_graphics_designer', hours: 61 }, { roleId: 'senior_producer', hours: 35 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'director_motion_graphics', hours: 2 }, { roleId: 'junior_motion_gfx_designer', hours: 2 }],
  },
  {
    id: 'ai_patient_video',
    category: 'Animation',
    name: 'AI Patient Video',
    description: 'Creation of AI Patient Video with minimal movement up to :60 Bumped Producer hrs up to 80.',
    oopDescription: '• Includes development and look and feel of characters and creation of art frames using Adobe Firefly up to 15 shots\n• Includes timing cut, 2D Animation created using combination of AI tools and traditional animation\n• Audio mix included. VO/Music costs not included',
    roleHours: [{ roleId: 'supervising_animation_director', hours: 125 }, { roleId: 'supervising_digital_artist', hours: 120 }, { roleId: 'senior_producer', hours: 115 }, { roleId: 'director_digital_art', hours: 30 }, { roleId: 'video_editor', hours: 16 }, { roleId: 'audio_engineer', hours: 12 }, { roleId: 'junior_video_editor', hours: 4 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'director_motion_graphics', hours: 2 }],
  },
  {
    id: '2d_whiteboard_animated_video',
    category: 'Animation',
    name: '2D Whiteboard Animated Video',
    description: 'Creation of (1) 2D Animated Whiteboard Video up to 5:00 ROUNDED UP PRODUCER HERS TO 110',
    oopDescription: '• Includes development and look and feel of characters and creation of art frames\n• Assumes Video Edit, 2D Animation \n• VO Record/Audio mix included. VO/Music costs not included',
    roleHours: [{ roleId: 'senior_digital_artist', hours: 240 }, { roleId: 'senior_producer', hours: 155 }, { roleId: 'senior_motion_graphics_designer', hours: 125 }, { roleId: 'director_digital_art', hours: 60 }, { roleId: 'video_editor', hours: 16 }, { roleId: 'audio_engineer', hours: 8 }, { roleId: 'junior_video_editor', hours: 4 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'director_motion_graphics', hours: 2 }, { roleId: 'dir_video_services_vp', hours: 1 }],
  },
  {
    id: 'kol_video_w_animation',
    category: 'Edit & Audio',
    name: 'KOL Video w/Animation',
    description: 'Post Production costs for 10 minute KOL hosted video. Production shoot to be estimated separately.',
    oopDescription: '(1) 10 minute KOL Video based in edit with animation passing assets to editor. Assumes graphics design layouts are created by agency art director. Includes scrolling ISI. **Estimate does not include costs for transcripts, talent, stock footage,stock music, hard drives etc and assumes those costs are covered on the Agency estimate.',
    roleHours: [{ roleId: 'senior_video_editor', hours: 80 }, { roleId: 'senior_producer', hours: 75 }, { roleId: 'senior_motion_graphics_designer', hours: 61 }, { roleId: 'junior_video_editor', hours: 20 }, { roleId: 'color_correct', hours: 16 }, { roleId: 'audio_engineer', hours: 8 }, { roleId: 'dir_video_services_vp', hours: 6 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'director_motion_graphics', hours: 2 }],
  },
  {
    id: 'patient_testimonial',
    category: 'Edit & Audio',
    name: 'Patient Testimonial',
    description: 'Post Production costs for 5 minute patient video. Production shoot to be estimated separately.',
    oopDescription: '"(1) 5 minute patient testimonial video. Multi camera shoot, basic animated supers and graphics/logos etc + animation of scrolling ISI. Music search, VO Record for ISI and music mix. Freelance color correct rates.Includes scrolling ISI. Assumes design of graphics by agency art director. Does not include talent or stock licensing costs.\n\n',
    roleHours: [{ roleId: 'senior_video_editor', hours: 80 }, { roleId: 'senior_producer', hours: 60 }, { roleId: 'senior_motion_graphics_designer', hours: 30 }, { roleId: 'junior_video_editor', hours: 20 }, { roleId: 'color_correct', hours: 16 }, { roleId: 'audio_engineer', hours: 8 }, { roleId: 'dir_video_services_vp', hours: 6 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'director_motion_graphics', hours: 2 }],
  },
  {
    id: 'live_action_sizzle_video',
    category: 'Edit & Audio',
    name: 'Live Action Sizzle Video',
    description: 'Full production 2-3 minute high energy video generated from existing content',
    oopDescription: 'Edit with heavy graphics. All assets and artwork provided by agency (stock imagery, PSD files, etc). Music search, pro VO talent record and final mix. Assumes all assets and artwork are provided by the agency. Does not Include talent or stock licensing costs.\n\n',
    roleHours: [{ roleId: 'senior_motion_graphics_designer', hours: 85 }, { roleId: 'senior_producer', hours: 65 }, { roleId: 'senior_video_editor', hours: 48 }, { roleId: 'junior_video_editor', hours: 12 }, { roleId: 'audio_engineer', hours: 5 }, { roleId: 'dir_video_services_vp', hours: 4 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'director_motion_graphics', hours: 2 }],
  },
  {
    id: 'tv_commercial',
    category: 'Edit & Audio',
    name: 'TV Commercial',
    description: 'Post Production costs for :60 TV. Production shoot to be estimated seperately.',
    oopDescription: 'In house edit, OOH broadcast audio record and mix bid thru SRX, OOH finishing bid thru SRX, general cleanup, no heavy VFX. All VFX will need to be assessed and estimated on a case by case basis.',
    oopItemName: 'Finishing',
    oopItemAmount: 40000,
    roleHours: [{ roleId: 'vp_executive_producer', hours: 200 }, { roleId: 'vp_assoc_dir', hours: 160 }, { roleId: 'senior_motion_graphics_designer', hours: 85 }, { roleId: 'junior_video_editor', hours: 40 }, { roleId: 'dir_video_services_vp', hours: 12 }, { roleId: 'svp_director_of_production', hours: 5 }, { roleId: 'director_motion_graphics', hours: 2 }],
  },
  {
    id: 'boardomatic',
    category: 'Edit & Audio',
    name: 'Boardomatic',
    description: 'Post Production costs for :60 Boardomatic. Artwork estimated separately Art creation not included, to be priced additionally if needed',
    oopDescription: '1 :60 straight boardomatic. Zooms, pans/scans, etc. 2D animated supers, logos etc. No heavy animation or layering of artwork for movement. Music search, professional VO record and final mix. Assumes all assets and artwork provided by agency. Includes no talent or stock licensing costs.',
    roleHours: [{ roleId: 'senior_video_editor', hours: 48 }, { roleId: 'senior_producer', hours: 45 }, { roleId: 'senior_motion_graphics_designer', hours: 30 }, { roleId: 'junior_video_editor', hours: 12 }, { roleId: 'audio_engineer', hours: 12 }, { roleId: 'dir_video_services_vp', hours: 4 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'director_motion_graphics', hours: 2 }],
  },
  {
    id: 'ai_boardomatic_standard',
    category: 'Edit & Audio',
    name: 'AI Boardomatic - STANDARD',
    description: 'Post Production costs for :60 Boardomatic. Includes creation of AI imagery Bumper Producer hrs to 45',
    oopDescription: '1 :60 straight boardomatic. Zooms, pans/scans, etc. 2D animated supers, logos etc. No video genertaion or heavy animation or layering of artwork for movement. Includes creation of AI imagery – up to 15 frames per video (estimated at 3 hrs per frame for creation/iterations)Music search, professional VO record and final mix. Includes no talent or stock licensing costs.',
    roleHours: [{ roleId: 'senior_producer', hours: 60 }, { roleId: 'senior_video_editor', hours: 48 }, { roleId: 'supervising_digital_artist', hours: 45 }, { roleId: 'senior_motion_graphics_designer', hours: 30 }, { roleId: 'junior_video_editor', hours: 12 }, { roleId: 'audio_engineer', hours: 12 }, { roleId: 'director_digital_art', hours: 12 }, { roleId: 'dir_video_services_vp', hours: 4 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'director_motion_graphics', hours: 2 }],
  },
  {
    id: 'ai_boardomatic_high_detail',
    category: 'Edit & Audio',
    name: 'AI Boardomatic - HIGH DETAIL',
    description: 'Post Production costs for :60 Boardomatic.Includes creation of AI imagery hig detail/hyper realism',
    oopDescription: '1 :60 straight boardomatic. Zooms, pans/scans, etc. 2D animated supers, logos etc. No video genertaion or heavy animation or layering of artwork for movement. Includes creation of AI imagery – up to 15 frames per video (estimated at 5 hrs per frame for creation/iterations)Music search, professional VO record and final mix. Includes no talent or stock licensing costs.',
    roleHours: [{ roleId: 'supervising_digital_artist', hours: 75 }, { roleId: 'senior_producer', hours: 72 }, { roleId: 'senior_video_editor', hours: 48 }, { roleId: 'senior_motion_graphics_designer', hours: 30 }, { roleId: 'director_digital_art', hours: 19 }, { roleId: 'junior_video_editor', hours: 12 }, { roleId: 'audio_engineer', hours: 12 }, { roleId: 'dir_video_services_vp', hours: 4 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'director_motion_graphics', hours: 2 }],
  },
  {
    id: 'animatic',
    category: 'Edit & Audio',
    name: 'Animatic',
    description: 'Post Production costs for :60 Animatic. Artwork estimated separately Art creation not included, to be priced additionally if needed',
    oopDescription: '1 :60 animatic. Assumes editor receives layered artwork from agency and handles the character animation as well as any supers/graphics within the spot. Music search, professional VO record and final mix. Assumes all assets and artwork provided by agency. Includes no talent or stock licensing costs.',
    roleHours: [{ roleId: 'senior_video_editor', hours: 96 }, { roleId: 'senior_producer', hours: 65 }, { roleId: 'senior_motion_graphics_designer', hours: 30 }, { roleId: 'junior_video_editor', hours: 24 }, { roleId: 'audio_engineer', hours: 12 }, { roleId: 'dir_video_services_vp', hours: 8 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'director_motion_graphics', hours: 2 }],
  },
  {
    id: 'ai_animatic_standard',
    category: 'Edit & Audio',
    name: 'AI Animatic - STANDARD',
    description: 'Post Production costs for :60 Animatic. Includes creation of AI imagery - **If AI video generation is needed up creation/iteration hrs to 6 per shot for generation. Rounded Producer hrs up to 80',
    oopDescription: 'Includes creation of AI imagery – up to 15 frames per video (estimated at 3 hrs per frame for creation/iterations) Includes 2D animated supers/logos\n Music search, professional VO record and final mix. Includes no talent or stock licensing costs.',
    roleHours: [{ roleId: 'senior_video_editor', hours: 96 }, { roleId: 'senior_producer', hours: 80 }, { roleId: 'supervising_digital_artist', hours: 45 }, { roleId: 'senior_motion_graphics_designer', hours: 30 }, { roleId: 'junior_video_editor', hours: 24 }, { roleId: 'audio_engineer', hours: 12 }, { roleId: 'director_digital_art', hours: 12 }, { roleId: 'dir_video_services_vp', hours: 8 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'director_motion_graphics', hours: 2 }],
  },
  {
    id: 'ai_animatic_high_detail',
    category: 'Edit & Audio',
    name: 'AI Animatic - HIGH DETAIL',
    description: 'Post Production costs for :60 Animatic. Includes creation of AI imagery Hgh detail/ Hyper Realism -- **If AI video generation is needed up creation/iteration hrs to 10 per shot for generation. Bumped to 65 hrs for Producer.',
    oopDescription: 'Includes creation of AI imagery – up to 15 frames per video (estimated at 5 hrs per frame for creation/iterations)\nIncludes 2D animated supers/logos\n Music search, professional VO record and final mix. Includes no talent or stock licensing costs.',
    roleHours: [{ roleId: 'senior_video_editor', hours: 96 }, { roleId: 'senior_producer', hours: 90 }, { roleId: 'supervising_digital_artist', hours: 75 }, { roleId: 'senior_motion_graphics_designer', hours: 30 }, { roleId: 'junior_video_editor', hours: 24 }, { roleId: 'director_digital_art', hours: 19 }, { roleId: 'audio_engineer', hours: 12 }, { roleId: 'dir_video_services_vp', hours: 8 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'director_motion_graphics', hours: 2 }],
  },
  {
    id: 'user_generated_content',
    category: 'Edit & Audio',
    name: 'User Generated Content',
    description: 'Editing user recorded videos (zoom, iphone, etc)',
    oopDescription: 'Editing up to 5 minutes of User Generated videos, indcluding reviews and revisions. Very light graphics if needed, no color correct, simple mix. Assumes all assets and artwork provided by agency. Includes no talent or stock licensing costs.',
    roleHours: [{ roleId: 'senior_video_editor', hours: 64 }, { roleId: 'senior_producer', hours: 45 }, { roleId: 'senior_motion_graphics_designer', hours: 21 }, { roleId: 'junior_video_editor', hours: 16 }, { roleId: 'dir_video_services_vp', hours: 5 }, { roleId: 'audio_engineer', hours: 5 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'director_motion_graphics', hours: 2 }],
  },
  {
    id: 'podcast',
    category: 'Edit & Audio',
    name: 'Podcast',
    description: 'Full Costs for 30 minute podcast (single episode)',
    oopDescription: '(2 ) 2 hour HD audio incomm record session w/Telepromter\n 30 minute podcast, audio edit and final mix. Assumes transcription cost is handled on the agency estimate.',
    oopItemName: 'Record',
    oopItemAmount: 1200,
    roleHours: [{ roleId: 'junior_video_editor', hours: 32 }, { roleId: 'senior_producer', hours: 25 }, { roleId: 'audio_engineer', hours: 4 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'dir_video_services_vp', hours: 2 }, { roleId: 'executive_producer', hours: 1 }],
  },
  {
    id: 'interactive_video_smartcast_production_post',
    category: 'Edit & Audio',
    name: 'Interactive Video (Smartcast) - Production/ Post',
    description: 'Build interactivity into a video. Assumes KOL shoot with accompanying animations. Assumes in house studio shoot with SRx DP & Director. Assumes medium complexity ask up to 20 videos, 2 paths.',
    oopDescription: '\n- Assumes use of VERSE interactive platform **Verse Fee to be included on agency estimate, not SRx bid.\n- Includes SRx studio shoot, in-house DP & Director. \n\n',
    oopItemName: 'Verse License',
    oopItemAmount: 12000,
    roleHours: [{ roleId: 'senior_motion_graphics_designer', hours: 145 }, { roleId: 'senior_video_editor', hours: 120 }, { roleId: 'senior_producer', hours: 115 }, { roleId: 'sr_developer', hours: 100 }, { roleId: 'associate_creative_director', hours: 60 }, { roleId: 'sr_product_manager', hours: 40 }, { roleId: 'qa', hours: 40 }, { roleId: 'junior_video_editor', hours: 30 }, { roleId: 'svp_director_virtual_events', hours: 20 }, { roleId: 'svp_director_of_technology', hours: 15 }, { roleId: 'dir_video_services_vp', hours: 9 }, { roleId: 'audio_engineer', hours: 8 }, { roleId: 'business_manager', hours: 5 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'director_motion_graphics', hours: 2 }],
  },
  {
    id: 'interactive_video_smartcast_post_only',
    category: 'Edit & Audio',
    name: 'Interactive Video (Smartcast) - Post Only',
    description: 'Build interactivity into a video. Assumes KOL shoot with accompanying animations. Assumes medium complexity ask up to 20 videos, 2 paths.',
    oopDescription: '\n- Assumes use of VERSE interactive platform. **Verse Fee to be included on agency estimate, not SRx bid\n\n\n',
    oopItemName: 'Verse License',
    oopItemAmount: 12000,
    roleHours: [{ roleId: 'senior_motion_graphics_designer', hours: 145 }, { roleId: 'senior_video_editor', hours: 120 }, { roleId: 'senior_producer', hours: 115 }, { roleId: 'sr_developer', hours: 100 }, { roleId: 'associate_creative_director', hours: 60 }, { roleId: 'sr_product_manager', hours: 40 }, { roleId: 'qa', hours: 40 }, { roleId: 'junior_video_editor', hours: 30 }, { roleId: 'svp_director_of_technology', hours: 15 }, { roleId: 'dir_video_services_vp', hours: 9 }, { roleId: 'audio_engineer', hours: 8 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'director_motion_graphics', hours: 2 }],
  },
  {
    id: 'radio',
    category: 'Edit & Audio',
    name: 'Radio',
    description: '(1) :60 Radio',
    oopDescription: '(1) Day record/mix, (1) Day Internal Revisions, (1/2) day Client Revisons, (1/2) Day Legal Revisions',
    oopItemName: 'Source Connect',
    oopItemAmount: 200,
    roleHours: [{ roleId: 'audio_engineer', hours: 24 }, { roleId: 'senior_producer', hours: 20 }, { roleId: 'svp_director_of_production', hours: 2 }],
  },
  {
    id: '360_video_moa',
    category: 'XR',
    name: '360 Video MOA',
    description: '3D Animated virtual reality experience 5 minutes in length. Estimated production costs possibly handled agency side. Producer time covers Post Production. If managing Production, additional hours will need to be added for oversite',
    oopDescription: '360 experiences could be either video or animated, but the key differentiator between 6DOF and 360 is that the user can not engage with the content or interact with any animated scenes besides looking left, right, up and down.\n360 videos can be deployed on:\nOnline 360-media players like YouTube360 or Facebook (Meta) 360.\nThe videos can also be implemented onto VR headsets like Quest 2, Pico VR, etc.\nWe can add interactive menu systems to VR headset tactics, but it will require some Unity dev work.\nHeadset costs are not included.',
    oopItemName: 'Production/Audio',
    oopItemAmount: 150000,
    roleHours: [{ roleId: 'senior_3d_artist', hours: 320 }, { roleId: 'senior_producer', hours: 215 }, { roleId: 'senior_motion_graphics_designer', hours: 85 }, { roleId: 'associate_creative_director', hours: 80 }, { roleId: 'director_computer_graphics', hours: 80 }, { roleId: 'xr_developer', hours: 80 }, { roleId: 'senior_xr_developer', hours: 40 }, { roleId: 'svp_director_experiential_development', hours: 30 }, { roleId: 'audio_engineer', hours: 16 }, { roleId: 'svp_director_of_production', hours: 5 }, { roleId: 'director_motion_graphics', hours: 2 }, { roleId: 'junior_motion_gfx_designer', hours: 2 }],
  },
  {
    id: 'unity_build_6dof_vr_experience',
    category: 'XR',
    name: 'Unity Build - 6DOF VR Experience',
    description: '',
    oopDescription: 'The user can move around on all axis (left, right, up, down, forward, backward, sideways, etc.) and can interact with selected items within the world.\nIt must be used with a VR headset. At a minimum, it is developed as a single-user experience but could be networked so that other users can be in the experience at the same time.\nHeadsets and computers are not included.',
    roleHours: [{ roleId: 'senior_producer', hours: 180 }, { roleId: 'senior_3d_artist', hours: 160 }, { roleId: 'xr_developer', hours: 160 }, { roleId: 'senior_xr_developer', hours: 120 }, { roleId: 'svp_director_experiential_development', hours: 70 }, { roleId: 'associate_creative_director', hours: 40 }, { roleId: 'director_computer_graphics', hours: 40 }, { roleId: 'audio_engineer', hours: 16 }, { roleId: 'svp_director_of_production', hours: 5 }, { roleId: 'junior_motion_gfx_designer', hours: 2 }],
  },
  {
    id: 'unity_build_interactive_game_non_vr',
    category: 'XR',
    name: 'Unity Build - Interactive Game Non-VR',
    description: '',
    oopDescription: 'This tactic doesn’t require the use of a VR headset. Can be deployed on an interactive wall or touchscreen.\n Equipment and computers are not included.\n• Example: Tepezza Interactive Wall',
    roleHours: [{ roleId: 'senior_producer', hours: 180 }, { roleId: 'senior_3d_artist', hours: 160 }, { roleId: 'xr_developer', hours: 160 }, { roleId: 'senior_xr_developer', hours: 120 }, { roleId: 'svp_director_experiential_development', hours: 70 }, { roleId: 'associate_creative_director', hours: 40 }, { roleId: 'director_computer_graphics', hours: 40 }, { roleId: 'audio_engineer', hours: 16 }, { roleId: 'svp_director_of_production', hours: 3 }, { roleId: 'junior_motion_gfx_designer', hours: 2 }],
  },
  {
    id: 'unity_build_online_virtual_metaverse',
    category: 'XR',
    name: 'Unity Build - Online Virtual/Metaverse',
    description: 'Online/Virtual Metaverse 3D platforms like Spatial, Meta Horizon World, Roblox, etc.',
    oopDescription: 'Users can move around (via an avatar) in this virtual 3D world, and interact with others and specific items. \n• Can be experienced online or immersive with a VR headset.\n Depending on the specific platform, Example - Write It Forward Metaverse on Spatial\n We can also build and develop our own virtual platforms. Example: IPG Health Metaverse\n Licensing / Publishing costs are not included.',
    roleHours: [{ roleId: 'senior_3d_artist', hours: 160 }, { roleId: 'senior_producer', hours: 130 }, { roleId: 'xr_developer', hours: 120 }, { roleId: 'associate_creative_director', hours: 40 }, { roleId: 'director_computer_graphics', hours: 40 }, { roleId: 'svp_director_experiential_development', hours: 40 }, { roleId: 'senior_xr_developer', hours: 40 }, { roleId: 'svp_director_of_production', hours: 3 }, { roleId: 'junior_motion_gfx_designer', hours: 2 }],
  },
  {
    id: 'social_ar_filter',
    category: 'XR',
    name: 'Social AR Filter',
    description: 'This is creating AR experiences using online platforms such as Instagram, Snapchat, Meta, TikTok, and other proven online social platforms now allowing AR functionalities.',
    oopDescription: 'Lighter development lift than the App Build AR tactic below. Example: Dentsply SureSmile Instagram AR filter.\no Licensing monthly costs are not included.',
    roleHours: [{ roleId: 'xr_developer', hours: 160 }, { roleId: 'senior_3d_artist', hours: 120 }, { roleId: 'senior_producer', hours: 115 }, { roleId: 'svp_director_experiential_development', hours: 40 }, { roleId: 'associate_creative_director', hours: 30 }, { roleId: 'director_computer_graphics', hours: 30 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'junior_motion_gfx_designer', hours: 2 }],
  },
  {
    id: 'app_build_ar',
    category: 'XR',
    name: 'App Build AR',
    description: 'A fully functional app with AR capabilities for a specific Congress and a device like an iPad. Bumped Producer hrs to 105',
    oopDescription: 'When we must create and develop a fully functional app with AR capabilities for a specific Congress and a device like an iPad. We could build an app that is public facing for users’ devices as well but we would need it to go through the App Store publishing process. Example of Congress-specific app builds: Pfizer Ritle AAD Magic Mirror AR.\n**Equipment costs are not included.',
    roleHours: [{ roleId: 'senior_producer', hours: 150 }, { roleId: 'senior_3d_artist', hours: 120 }, { roleId: 'senior_xr_developer', hours: 120 }, { roleId: 'xr_developer', hours: 120 }, { roleId: 'associate_creative_director', hours: 60 }, { roleId: 'svp_director_experiential_development', hours: 60 }, { roleId: 'director_computer_graphics', hours: 30 }, { roleId: 'audio_engineer', hours: 8 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'junior_motion_gfx_designer', hours: 2 }],
  },
  {
    id: 'web_ar',
    category: 'XR',
    name: 'Web AR',
    description: 'This is creating AR experiences using online platforms such as 8th Wall. Bumped Producer hrs to 85',
    oopDescription: '"Similar to the App Build AR but will be web based, and will work within a mobile browser. CAVEAT - NEEDS DIGITAL DEV (HTML) WEBSITE HOURS. Example: Jynarque AR\n**Licensing monthly costs are not included."',
    oopItemName: 'Subsciption',
    oopItemAmount: 3000,
    roleHours: [{ roleId: 'xr_developer', hours: 160 }, { roleId: 'senior_producer', hours: 120 }, { roleId: 'senior_3d_artist', hours: 120 }, { roleId: 'associate_creative_director', hours: 60 }, { roleId: 'svp_director_experiential_development', hours: 40 }, { roleId: 'director_computer_graphics', hours: 30 }, { roleId: 'audio_engineer', hours: 8 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'junior_motion_gfx_designer', hours: 2 }],
  },
  {
    id: 'low_complexity_2d_medical_art',
    category: 'Digital Art',
    name: 'Low Complexity 2D Medical Art',
    description: '',
    oopDescription: 'Includes medical research time and supervision• Includes time for creation of relevant moodboards, pencil sketches, and final art\n**Asumes SRx Producer led model with no hours for agency producer- Includes reskinning asks- Low complexity medical story tellingand/or- low complexity 2D style-Can be vector or raster- Single image or small series of images',
    roleHours: [{ roleId: 'digital_artist', hours: 40 }, { roleId: 'senior_producer', hours: 30 }, { roleId: 'director_digital_art', hours: 13 }, { roleId: 'senior_digital_artist', hours: 10 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'assistant_motion_gfx_designer', hours: 2 }],
  },
  {
    id: 'high_complexity_2d_medical_art',
    category: 'Digital Art',
    name: 'High Complexity 2D Medical Art',
    description: 'Assumes creation of (1) 2D image',
    oopDescription: '• Includes medical research time and supervision• Includes time for creation of relevant moodboards, pencil sketches, and final art\n**Asumes SRx Producer led model with no hours for agency producer- high complexity medical story tellingand/or- high complexity style- Single image or series of images-Can be vector or raster- May include more environment',
    roleHours: [{ roleId: 'digital_artist', hours: 64 }, { roleId: 'senior_producer', hours: 45 }, { roleId: 'senior_digital_artist', hours: 24 }, { roleId: 'director_digital_art', hours: 22 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'assistant_motion_gfx_designer', hours: 2 }],
  },
  {
    id: 'low_complexity_3d_medical_art',
    category: 'Digital Art',
    name: 'Low Complexity 3D Medical Art',
    description: 'Assumes creation of (1) 2D image',
    oopDescription: '• Includes medical research time and supervision• Includes time for creation of relevant moodboards, pencil sketches, 3D models and Final art\n**Asumes SRx Producer led model with no hours for agency producer-includes time for modeling, lighting rendering and final retouching- low complexity medical story tellingand/or- low complexity 3D style- Single image or small series of images.',
    roleHours: [{ roleId: 'senior_3d_artist', hours: 64 }, { roleId: 'senior_producer', hours: 40 }, { roleId: 'director_computer_graphics', hours: 16 }, { roleId: 'supervising_medical_illustrator', hours: 16 }, { roleId: 'director_digital_art', hours: 4 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'assistant_motion_gfx_designer', hours: 2 }],
  },
  {
    id: 'high_complexity_3d_medical_art',
    category: 'Digital Art',
    name: 'High Complexity 3D Medical Art',
    description: 'Assumes creation of (1) 3D image',
    oopDescription: '• Includes medical research time and supervision• Includes time for creation of relevant moodboards, pencil sketches, 3D models and Final art\n**Asumes SRx Producer led model with no hours for agency producer- high complexity medical story tellingand/or- high complexity 3D style- Single image or series of images- May include more environment',
    roleHours: [{ roleId: 'senior_3d_artist', hours: 96 }, { roleId: 'senior_producer', hours: 65 }, { roleId: 'supervising_medical_illustrator', hours: 40 }, { roleId: 'director_computer_graphics', hours: 24 }, { roleId: 'director_digital_art', hours: 11 }, { roleId: 'digital_artist', hours: 4 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'assistant_motion_gfx_designer', hours: 2 }],
  },
  {
    id: 'instructional_stills',
    category: 'Digital Art',
    name: 'Instructional Stills',
    description: 'Instructional Stills',
    oopDescription: '• Includes medical research time and supervision• Includes time for creation of relevant moodboards, pencil sketches, and final art\n**Asumes SRx Producer led model with no hours for agency producer-Assumes 10 medium complexity stills without MOA elements',
    roleHours: [{ roleId: 'digital_artist', hours: 56 }, { roleId: 'senior_producer', hours: 40 }, { roleId: 'director_digital_art', hours: 18 }, { roleId: 'senior_digital_artist', hours: 14 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'assistant_motion_gfx_designer', hours: 2 }],
  },
  {
    id: 'instructional_boards',
    category: 'Digital Art',
    name: 'Instructional Boards',
    description: 'Assumes creation of (1) 3D image',
    oopDescription: '• Includes pencil sketches, and final art. Assumes 25-30 frames\n**Asumes SRx Producer led model with no hours for agency producer-Assumes boards for 2 minute video without MOA elements- Medium to tight pencils - rough layering for animatic uses',
    roleHours: [{ roleId: 'digital_artist', hours: 48 }, { roleId: 'senior_producer', hours: 30 }, { roleId: 'director_digital_art', hours: 12 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'assistant_motion_gfx_designer', hours: 2 }],
  },
  {
    id: 'instructional_frames_for_animation',
    category: 'Digital Art',
    name: 'Instructional Frames for animation',
    description: 'Assumes creation of (1) 3D image',
    oopDescription: '• Includes medical research time and supervision• Includes time for creation of relevant moodboards, pencil sketches, and final art\n**Asumes SRx Producer led model with no hours for agency producer-Assumes storyboards and final art for 2 minute video without MOA elements- Medium complexity style -Layered and prepped for animation',
    roleHours: [{ roleId: 'digital_artist', hours: 120 }, { roleId: 'senior_producer', hours: 60 }, { roleId: 'director_digital_art', hours: 33 }, { roleId: 'senior_digital_artist', hours: 12 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'assistant_motion_gfx_designer', hours: 2 }],
  },
  {
    id: 'single_device_syringes_inhalers_injectors_misc',
    category: 'Digital Art',
    name: 'Single Device - Syringes, Inhalers, Injectors, Misc.',
    description: '',
    oopDescription: 'Preliminary prep for animationDoes not include particle/fluid simulationReceiving accurate mechanicalsReceiving physicals objects No CGI handsDelivery of jpeg exports and layered working files, (object, shadow, background, any transparency) up to 10 views for devices. Assumes SRX producer led model. 3 rounds of revisions',
    roleHours: [{ roleId: 'senior_3d_artist', hours: 80 }, { roleId: 'senior_producer', hours: 40 }, { roleId: 'director_computer_graphics', hours: 20 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'assistant_motion_gfx_designer', hours: 2 }],
  },
  {
    id: 'product_shots_cgi',
    category: 'Digital Art',
    name: 'Product Shots CGI',
    description: 'Without supplied CAD/Step/SolidWorks files:',
    oopDescription: 'Product - Capsules, Gel pills, Pressed pills, Vials Package - Blister packs, Boxes, Bottles, Tubes AssumptionsReceiving accurate mechanicalsReceiving physicals objects No CGI hands Delivery of jpeg exports and layered working files, (object, shadow, background, any transparency \n \nagency supplies label print files in either outlined Illustrator or PDF format\nagency supplies actual product to use as reference for modeling the products\n \nassumes 10 views. 4 dosage label versions.\n40 images\n \n10 days modeling and texturing, rig for animation\n5 days lighting, rendering, PSD preparation\n \ncreative review revisions\n3 days. **Can be scaled down if deliverables list is smaller"',
    roleHours: [{ roleId: 'senior_3d_artist', hours: 184 }, { roleId: 'senior_producer', hours: 80 }, { roleId: 'director_computer_graphics', hours: 56 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'assistant_motion_gfx_designer', hours: 2 }],
  },
  {
    id: 'product_shots_cgi_2',
    category: 'Digital Art',
    name: 'Product Shots CGI',
    description: 'With supplied CAD/Step/SolidWorks files:',
    oopDescription: 'Product - Capsules, Gel pills, Pressed pills, Vials Package - Blister packs, Boxes, Bottles, Tubes agency supplies label print files in either outlined Illustrator or PDF format\n \nassumes 10 views. 4 dosage label versions.\n40 images\n \n2 days model clean up and texturing, rig for animation\n5 days lighting, rendering, PSD preparation\n \ncreative review revisions\n3 days\n \n2x client review revisions\n2.5 days each\n',
    roleHours: [{ roleId: 'senior_3d_artist', hours: 120 }, { roleId: 'senior_producer', hours: 55 }, { roleId: 'director_computer_graphics', hours: 30 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'assistant_motion_gfx_designer', hours: 2 }],
  },
  {
    id: 'low_complexity_comp_art',
    category: 'Digital Art',
    name: 'Low Complexity Comp Art',
    description: '',
    oopDescription: 'Assumes SRX producer led model 3 rounds of revisionTight idea coming from the team including a set lockupAll relevant assets provided from team including stock assets, branding colors, Vector files for any text assets that are part of the artMinimal to no SRX sketchingLess involved rendering style',
    roleHours: [{ roleId: 'senior_producer', hours: 16 }, { roleId: 'senior_digital_artist', hours: 16 }, { roleId: 'director_digital_art', hours: 4 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'assistant_motion_gfx_designer', hours: 2 }],
  },
  {
    id: 'high_complexity_comp_art',
    category: 'Digital Art',
    name: 'High Complexity Comp Art',
    description: '',
    oopDescription: 'Assumes SRX producer led model 3 rounds of revision. Can be a looser idea coming from the teamCan include relevant moodboarding/style directionRelevant assets provided from team including stock assets, branding colors, Vector files for any text assets that are part of the art. Can work with team to identify appropriate stock. Stock is not licensed through SRXCan include a round SRX sketchingMore involved rendering style, including mutli-discipline art',
    roleHours: [{ roleId: 'senior_digital_artist', hours: 48 }, { roleId: 'senior_producer', hours: 30 }, { roleId: 'director_digital_art', hours: 12 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'assistant_motion_gfx_designer', hours: 2 }],
  },
  {
    id: '2d_campaign_key_art',
    category: 'Digital Art',
    name: '2D Campaign / Key art',
    description: '',
    oopDescription: '3 rounds revision sketches 3 rounds revision on final art Delivery of final art exports and working filesVector, raster, or PhotocompositingDoes not assume prepping for motion or for proofsAssumes team provides and licenses all stock assets. One piece of key art, or two pieces of key art with slight variations. Team is responsible for text layout and lock ups. Assumes any relevant Moodboards',
    roleHours: [{ roleId: 'senior_digital_artist', hours: 80 }, { roleId: 'senior_producer', hours: 55 }, { roleId: 'digital_artist', hours: 32 }, { roleId: 'director_digital_art', hours: 28 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'assistant_motion_gfx_designer', hours: 2 }],
  },
  {
    id: '3d_campaign_art',
    category: 'Digital Art',
    name: '3D Campaign art',
    description: '',
    oopDescription: 'Assumes any relevant Moodboards 2 rounds revision for sketches 1 round revision on clay 2 rounds lighting/texture 2 Rounds revision on final (full retouching/compositing)Delivery of final art exports at standard print res and working files (Raster Photoshop file)Does not assume prepping for motion or for print proofsAssumes team provides and licenses all stock assets. One piece of key art, or two pieces of key art with slight variations. Team is responsible for text layout and lock ups.',
    roleHours: [{ roleId: 'senior_3d_artist', hours: 136 }, { roleId: 'senior_producer', hours: 80 }, { roleId: 'senior_digital_artist', hours: 48 }, { roleId: 'director_computer_graphics', hours: 34 }, { roleId: 'director_digital_art', hours: 12 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'assistant_motion_gfx_designer', hours: 2 }],
  },
  {
    id: 'interactive_virtual_broadcast_level_1',
    category: 'Live & Virtual Events',
    name: 'Interactive Virtual Broadcast Level 1',
    description: 'Standard Graphics Package - Presenters at Home, Zoom. Cost includes 1 presenter.',
    oopDescription: '• Virtual Record (Streamyard record) / SMARTCAST\n',
    oopItemName: 'Production',
    oopItemAmount: 300,
    roleHours: [{ roleId: 'senior_motion_graphics_designer', hours: 65 }, { roleId: 'senior_producer', hours: 60 }, { roleId: 'senior_video_editor', hours: 40 }, { roleId: 'junior_video_editor', hours: 10 }, { roleId: 'audio_engineer', hours: 8 }, { roleId: 'svp_director_virtual_events', hours: 5 }, { roleId: 'dir_video_services_vp', hours: 3 }, { roleId: 'business_manager', hours: 3 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'director_motion_graphics', hours: 2 }],
  },
  {
    id: 'interactive_virtual_broadcast_level_2',
    category: 'Live & Virtual Events',
    name: 'Interactive Virtual Broadcast - Level 2',
    description: 'Standard Graphics Package - Presenters at Home, Drop Kit. Cost includes 1 Presenter/1 Drop Kit.',
    oopDescription: 'Single 1 camera Drop Kit is priced on the high end. Can be reduced - Hayden5 (baseline of $10k-$12k) or Remote Control ($7k-$9k) **$2300 of OOP is for Big Marker platform webinar',
    oopItemName: 'Production',
    oopItemAmount: 14300,
    roleHours: [{ roleId: 'senior_motion_graphics_designer', hours: 65 }, { roleId: 'senior_producer', hours: 60 }, { roleId: 'senior_video_editor', hours: 40 }, { roleId: 'svp_director_virtual_events', hours: 10 }, { roleId: 'executive_producer', hours: 10 }, { roleId: 'junior_video_editor', hours: 10 }, { roleId: 'audio_engineer', hours: 8 }, { roleId: 'dir_video_services_vp', hours: 3 }, { roleId: 'business_manager', hours: 3 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'director_motion_graphics', hours: 2 }],
  },
  {
    id: 'interactive_virtual_broadcast_level_3',
    category: 'Live & Virtual Events',
    name: 'Interactive Virtual Broadcast- Level 3',
    description: 'Standard Graphics Package - Presenters in same studio. Assumes (1) shoot day.',
    oopDescription: 'STUDIO BROADCAST - Range could be $10k-$20k per shoot day (w/crew, equipment, etv) **$2300 of OOP is for Big Marker platform webinar',
    oopItemName: 'Production',
    oopItemAmount: 22300,
    roleHours: [{ roleId: 'svp_director_virtual_events', hours: 70 }, { roleId: 'senior_motion_graphics_designer', hours: 65 }, { roleId: 'senior_producer', hours: 60 }, { roleId: 'senior_video_editor', hours: 40 }, { roleId: 'executive_producer', hours: 10 }, { roleId: 'junior_video_editor', hours: 10 }, { roleId: 'audio_engineer', hours: 8 }, { roleId: 'business_manager', hours: 7 }, { roleId: 'dir_video_services_vp', hours: 3 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'director_motion_graphics', hours: 2 }],
  },
  {
    id: 'interactive_virtual_broadcast_level_4',
    category: 'Live & Virtual Events',
    name: 'Interactive Virtual Broadcast - Level 4',
    description: 'Standard Graphics Package - Presenters in separate studios / locations. Assumes 3 presenters. Assumes (1) shoot day.',
    oopDescription: 'STUDIO BROADCAST MULTIPLE LOCATIONS - $35-$55k, per shoot day. **$2300 of OOP is for Big Marker platform webinar',
    oopItemName: 'Production',
    oopItemAmount: 57300,
    roleHours: [{ roleId: 'svp_director_virtual_events', hours: 70 }, { roleId: 'senior_motion_graphics_designer', hours: 65 }, { roleId: 'senior_producer', hours: 60 }, { roleId: 'executive_producer', hours: 40 }, { roleId: 'senior_video_editor', hours: 40 }, { roleId: 'junior_video_editor', hours: 10 }, { roleId: 'audio_engineer', hours: 8 }, { roleId: 'business_manager', hours: 7 }, { roleId: 'dir_video_services_vp', hours: 3 }, { roleId: 'svp_director_of_production', hours: 2 }, { roleId: 'director_motion_graphics', hours: 2 }],
  },
  {
    id: 'on_location_shoots_interviews',
    category: 'Live & Virtual Events',
    name: 'On Location Shoots / Interviews',
    description: 'Assuming domestic, no studio location, using mostly local crew. Includes hours for Director travel time, day of shoot and return. **Post time to be scoped additionally based upon project ask',
    oopDescription: 'Assumes Tri State. Does NOT include hard travel costs for SRX - airfare, hotel, per diem. If needed, costs to be added additionally',
    oopItemName: 'Production',
    oopItemAmount: 18000,
    roleHours: [{ roleId: 'svp_director_virtual_events', hours: 40 }, { roleId: 'business_manager', hours: 7 }],
  },
  {
    id: 'in_studio_33rd_st_or_parsippany_nj_shoots',
    category: 'Live & Virtual Events',
    name: 'In Studio (33rd St or Parsippany, NJ) Shoots',
    description: 'Interviews/Product Shoots **Post time to be scoped additionally based upon project ask',
    oopDescription: 'In Studio (33rd Street or Parsippany, NJ) shoots - interviews, product shoots',
    oopItemName: 'Production',
    oopItemAmount: 2000,
    roleHours: [{ roleId: 'svp_director_virtual_events', hours: 20 }, { roleId: 'business_manager', hours: 5 }],
  },
  {
    id: 'in_studio_ooh_shoots',
    category: 'Live & Virtual Events',
    name: 'In Studio (OOH) Shoots',
    description: 'Interviews/Product Shoots **Post time to be scoped additionally based upon project ask',
    oopDescription: 'Assumes Tri State. Does NOT include hard travel costs for SRX - airfare, hotel, per diem. If needed, costs to be added additionally if needed',
    oopItemName: 'Production',
    oopItemAmount: 20000,
    roleHours: [{ roleId: 'svp_director_virtual_events', hours: 40 }, { roleId: 'business_manager', hours: 7 }],
  },
];

export const createProjectFromBenchmark = (tactic: BenchmarkTactic, baseEstimateNumber: string): Project => {
  const executionPhase: CustomPhase = {
    id: `phase-exec-${Date.now()}`,
    name: 'Product Execution',
    roles: tactic.roleHours.map(rh => ({ roleId: rh.roleId, hours: rh.hours })),
  };
  const oopCosts: OopCost[] = tactic.oopItemName
    ? [{ id: `oop-${Date.now()}`, name: tactic.oopItemName, amount: tactic.oopItemAmount || 0 }]
    : [];
  return {
    id: `project-benchmark-${Date.now()}`,
    estimateNumber: baseEstimateNumber,
    baseEstimateNumber,
    details: {
      projectName: tactic.name,
      client: 'Standard',
      brand: '',
      jobNumber: `JOB-${new Date().getFullYear()}-${Math.floor(100 + Math.random() * 900)}`,
      estimatePreparedBy: '',
      businessManager: '',
      agency: '',
      scopeOfWork: tactic.description,
    },
    phases: [createProductionManagementPhase(), executionPhase],
    oopCosts,
    contingencyPercent: 0,
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
};